FROM python:3.9

WORKDIR /app

COPY requirements.txt ./requirements.txt

RUN apt-get update \
        && apt-get install libportaudio2 libportaudiocpp0 portaudio19-dev libsndfile1-dev -y \
        && pip3 install pyaudio

RUN pip install -r requirements.txt

EXPOSE 8501

WORKDIR /src
COPY . /src

ENTRYPOINT ["streamlit", "run"]

CMD ["src/main.py"]